FROM ubuntu:20.04

RUN apt-get update \
    && apt-get install -y \
                deluged \
                deluge-web \
                deluge-console \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD /usr/bin/deluged & /usr/bin/deluge-web & /bin/bash
