version: "3.9"
services:
  wireguard:
    build: wireguard
    privileged: true
    ports:
      - "6891:6891"
      - "8112:8112"
    restart: always
  deluge:
    depends_on:
      - wireguard
    build: deluge
    network_mode: service:wireguard
    volumes:
      - ${HOME}/.config/deluge/:/root/.config/deluge/:cached
      - ${HOME}/Downloads/:/root/Downloads/:cached
    restart: always
  plex:
    image: lscr.io/linuxserver/plex:arm32v7-latest
    network_mode: host
    volumes:
      - ${HOME}/.config/plex/:/config:cached
      - ${HOME}/Movies/:/movies:cached
    environment:
      - VERSION=docker
    restart: always
