version: "3.9"
services:
  wireguard:
    build: wireguard
    privileged: true
    ports:
      - "0.0.0.0:8112:8112"
    restart: unless-stopped
  deluge:
    depends_on:
      - wireguard
    build: deluge
    network_mode: service:wireguard
    volumes:
      - ${HOME}/.config/deluge/:/root/.config/deluge/:cached
      - ${HOME}/Downloads/:/root/Downloads/:cached
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:arm32v7-latest
    network_mode: host
    volumes:
      - ${HOME}/.config/plex/:/config:cached
      - ${HOME}/Movies/:/movies:cached
    environment:
      - VERSION=docker
    restart: unless-stopped
  samba:
    build: samba
    network_mode: host
    volumes:
      - ${HOME}/Public/:/samba/PUBLIC
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
  earnapp:
    build: earnapp
  grafana:
    build: grafana
    network_mode: host
    volumes:
      - /var/log:/var/log