version: "3.9"
services:
  wireguard:
    build: wireguard
    privileged: true
    ports:
      - "0.0.0.0:8112:8112"
    restart: unless-stopped
  deluge:
    depends_on:
      - wireguard
    build: deluge
    network_mode: service:wireguard
    volumes:
      - /home/pi/.config/deluge/:/home/deluge/.config/deluge/
      - /media/external/deluge/:/home/deluge/Downloads/
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:arm32v7-latest
    network_mode: host
    volumes:
      - /home/pi/.config/plex/:/config/
      - /media/external/deluge/:/movies
    environment:
      - VERSION=docker
    restart: unless-stopped
  samba:
    build: samba
    network_mode: host
    volumes:
      - /media/external/:/samba/PUBLIC
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
  grafana:
    build: grafana
    network_mode: host
    volumes:
      - /var/log:/var/log
      - /media/external/:/media/external/:ro